variable "env" {}
variable "vpc" {}
variable "default_vpc_id" {}
variable "subnets" {}
#variable "docdb" {}
#variable "rds" {}
#variable "elasticache" {}
#variable "rabbitmq" {}
#variable "alb" {}
#variable "apps" {}
#variable "bastion_cidr" {}